### ISSUE TITLE
Prepare terraform 0.13

### ISSUE THREAD

**Issue by YuSungDuk** [NaverCloudPlatform/terraform-provider-ncloud#15]
- [x] Step 1: Moving your provider from ​terraform-providers​ to a repository in your company's GitHub organization namespace. Complete instructions for this step are attached to this [email](https://docs.google.com/document/d/e/2PACX-1vQuwJP2JWrFYM2IiPQxw-Qv-t76sQAAh5iLRht2pNUw0oHCRqMUjdHhm3DMTKx48Vz_Hp7lo1LD9OJG/pub), and are also available ​here​ for review.
- [x] Step 2: Prepare and publish your provider to the Registry. Full instructions for publishing Providers to the Registry are available in our documentation ​[here](https://www.terraform.io/docs/registry/providers/publishing.html)​.
- [x] Step 3: Verify that your integration is listed on our integrations catalog ​[here](https://www.hashicorp.com/integrations/)​.​ If not, please reach out to ​partners@hashicorp.com​ and we will be happy to work with you on adding your integration.

**Comment by YuSungDuk** [comment]
https://registry.terraform.io/v1/providers/terraform-providers/ncloud/versions

**Comment by sangkyu-kim** [comment]
Due to the effect of step1, it is necessary for ncloud users to upgrade to terraform 0.13

#### How will this affect users on 0.12 versions of Terraform, if my Provider was previously trusted via /terraform-providers?
- As part of the transfer and publishing process for existing Partner providers, we are re-signing so that existing users are unaffected and can continue to install directly from within Terraform CLI.


#### What happens if I’m a Partner and am unable to move our Provider by July 31st?
- The main impact is that users running upgrade013 will have your Provider's namespace configured automatically in their required_providers source configuration by the upgrade tool. However when you then later migrate namespaces, those same users will encounter an error on init until they manually update the provider_source. We are trying to avoid this extra step, especially for those relying on many Providers.
